#!/bin/sh

#Set up the zip dirs/filenames for our manifest
dirs=`for i in $(ls -d *_*/); do echo ${i%%/}; done`
zips=`for i in $(ls -d *_*/); do echo ${i%%/}.zip; done`

#regenerate zips from the dirs.
rm -f ${zips}
for i in ${dirs}; do
	zip -oqr ${i} ${i}
done

#regenerate package.
zip -oq pkg_natural.zip pkg_natural.xml ${zips}

#remove unwanted zips.
rm -f ${zips}
exit 0
