#!/bin/sh

#Set up the zip dirs/filenames for our manifest
dirs=`for i in $(ls -d *_*/); do echo ${i%%/}; done`
zips=`for i in $(ls -d *_*/); do echo ${i%%/}.zip; done`

#regenerate zips from the dirs.
rm -f ${zips}
for i in ${dirs}; do
	zip -oqr ${i} ${i}
done

#regenerate the contender package.
zip -oq new_natural.zip pkg_natural.xml ${zips}

#get an md5 of both the original pkg and the contender.
mnew=`stat -f "%m%t%Sm %N" new_natural.zip | sed 's/new_natural.zip/pkg_natural.zip/'`
mpkg=`stat -f "%m%t%Sm %N" pkg_natural.zip`

#update pkg if needs be. otherwise reset
if [ "${mnew}" != "${mpkg}" ]; then
	echo "${mnew} is different from "
	echo "${mpkg}"
	mv new_natural.zip pkg_natural.zip
else
	rm new_natural.zip
fi
#remove unwanted zips.
rm -f ${zips}
exit 0


